USE DATABASE AIRLINE_EDW;
USE SCHEMA AIRLINE_EDW.SILVER;

CREATE OR REPLACE PROCEDURE LOAD_CLEAN_DATA()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    rows_loaded INT;
BEGIN

    MERGE INTO SILVER.CLEAN t
    USING (
        SELECT *
        FROM (
            SELECT
                PASSENGER_ID,
                TRIM(FIRST_NAME) AS FIRST_NAME,
                TRIM(LAST_NAME) AS LAST_NAME,
                UPPER(GENDER) AS GENDER,
                TRY_CAST(AGE AS INT) AS AGE,
                TRIM(NATIONALITY) AS NATIONALITY,
                TRIM(AIRPORT_NAME) AS AIRPORT_NAME,
                UPPER(AIRPORT_COUNTRY_CODE) AS AIRPORT_COUNTRY_CODE,
                TRIM(COUNTRY_NAME) AS COUNTRY_NAME,
                UPPER(AIRPORT_CONTINENT) AS AIRPORT_CONTINENT,
                UPPER(CONTINENTS) AS CONTINENTS,
                TO_DATE(DEPARTURE_DATE) AS DEPARTURE_DATE,
                TRIM(ARRIVAL_AIRPORT) AS ARRIVAL_AIRPORT,
                TRIM(PILOT_NAME) AS PILOT_NAME,
                UPPER(FLIGHT_STATUS) AS FLIGHT_STATUS,
                UPPER(TICKET_TYPE) AS TICKET_TYPE,
                UPPER(PASSENGER_STATUS) AS PASSENGER_STATUS,
                
                ROW_NUMBER() OVER (PARTITION BY PASSENGER_ID ORDER BY PASSENGER_ID) AS rn
            FROM BRONZE.BRONZE_STREAM
            WHERE PASSENGER_ID IS NOT NULL
        )
        WHERE rn = 1
    ) s
    ON t.PASSENGER_ID = s.PASSENGER_ID

    WHEN MATCHED THEN UPDATE SET
        FIRST_NAME = s.FIRST_NAME,
        LAST_NAME = s.LAST_NAME,
        GENDER = COALESCE(s.GENDER, 'UNKNOWN'),
        AGE = COALESCE(s.AGE, 0),
        NATIONALITY = COALESCE(s.NATIONALITY, 'UNKNOWN'),
        AIRPORT_NAME = s.AIRPORT_NAME,
        AIRPORT_COUNTRY_CODE = COALESCE(s.AIRPORT_COUNTRY_CODE, 'UNK'),
        COUNTRY_NAME = COALESCE(s.COUNTRY_NAME, 'UNKNOWN'),
        AIRPORT_CONTINENT = COALESCE(s.AIRPORT_CONTINENT, 'UNK'),
        CONTINENTS = COALESCE(s.CONTINENTS, 'UNK'),
        DEPARTURE_DATE = s.DEPARTURE_DATE,
        ARRIVAL_AIRPORT = COALESCE(s.ARRIVAL_AIRPORT, 'UNKNOWN'),
        PILOT_NAME = s.PILOT_NAME,
        FLIGHT_STATUS = COALESCE(s.FLIGHT_STATUS, 'UNKNOWN'),
        TICKET_TYPE = COALESCE(s.TICKET_TYPE, 'UNKNOWN'),
        PASSENGER_STATUS = COALESCE(s.PASSENGER_STATUS, 'UNKNOWN')

    WHEN NOT MATCHED THEN INSERT VALUES (
    s.PASSENGER_ID, s.FIRST_NAME, s.LAST_NAME, s.GENDER, COALESCE(s.AGE,0),
    COALESCE(s.NATIONALITY,'UNKNOWN'), s.AIRPORT_NAME,
    COALESCE(s.AIRPORT_COUNTRY_CODE,'UNK'),
    COALESCE(s.COUNTRY_NAME,'UNKNOWN'),
    COALESCE(s.AIRPORT_CONTINENT,'UNK'),
    COALESCE(s.CONTINENTS,'UNK'),
    s.DEPARTURE_DATE,
    COALESCE(s.ARRIVAL_AIRPORT,'UNKNOWN'),
    s.PILOT_NAME,
    COALESCE(s.FLIGHT_STATUS,'UNKNOWN'),
    COALESCE(s.TICKET_TYPE,'UNKNOWN'),
    COALESCE(s.PASSENGER_STATUS,'UNKNOWN')
);

    rows_loaded := SQLROWCOUNT;

    INSERT INTO OPERATIONS.AUDIT_LOG 
    (SCHEMA_NAME, PIPELINE_STAGE, ROWS_AFFECTED, STATUS)
    VALUES ('SILVER', 'BRONZE_TO_SILVER', :rows_loaded, 'SUCCESS');

    RETURN 'Silver Load Complete. Rows merged: ' || :rows_loaded;

END;
$$;