USE DATABASE AIRLINE_EDW;
USE SCHEMA AIRLINE_EDW.GOLD;

CREATE OR REPLACE PROCEDURE GOLD.LOAD_STAR_SCHEMA()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    rows_affected INT;
BEGIN
    BEGIN TRANSACTION;

    -- Stage filtered stream data
    CREATE OR REPLACE TEMP TABLE GOLD.TMP_DATA AS
    SELECT *
    FROM SILVER.SILVER_STREAM
    WHERE METADATA$ACTION = 'INSERT'
      AND METADATA$ISUPDATE = FALSE;

    -- DIM_PASSENGER
    MERGE INTO GOLD.DIM_PASSENGER t
    USING (
        SELECT 
            PASSENGER_ID, FIRST_NAME, LAST_NAME, GENDER, AGE, NATIONALITY
        FROM GOLD.TMP_DATA
        WHERE PASSENGER_ID IS NOT NULL
        QUALIFY ROW_NUMBER() OVER (
            PARTITION BY PASSENGER_ID 
            ORDER BY DEPARTURE_DATE DESC
        ) = 1
    ) s
    ON t.PASSENGER_ID = s.PASSENGER_ID
    WHEN MATCHED THEN UPDATE SET
        FIRST_NAME = s.FIRST_NAME,
        LAST_NAME = s.LAST_NAME,
        GENDER = s.GENDER,
        AGE = s.AGE,
        NATIONALITY = s.NATIONALITY
    WHEN NOT MATCHED THEN INSERT (
        PASSENGER_ID, FIRST_NAME, LAST_NAME, GENDER, AGE, NATIONALITY
    )
    VALUES (
        s.PASSENGER_ID, s.FIRST_NAME, s.LAST_NAME,
        s.GENDER, s.AGE, s.NATIONALITY
    );

    -- DIM_AIRPORT
    MERGE INTO GOLD.DIM_AIRPORT t
    USING (
        SELECT 
            AIRPORT_NAME, AIRPORT_COUNTRY_CODE, COUNTRY_NAME, AIRPORT_CONTINENT
        FROM GOLD.TMP_DATA
        WHERE AIRPORT_NAME IS NOT NULL
        QUALIFY ROW_NUMBER() OVER (
            PARTITION BY AIRPORT_NAME, AIRPORT_COUNTRY_CODE
            ORDER BY DEPARTURE_DATE DESC
        ) = 1
    ) s
    ON t.AIRPORT_NAME = s.AIRPORT_NAME
       AND t.AIRPORT_COUNTRY_CODE = s.AIRPORT_COUNTRY_CODE
    WHEN NOT MATCHED THEN INSERT (
        AIRPORT_NAME, AIRPORT_COUNTRY_CODE, COUNTRY_NAME, AIRPORT_CONTINENT
    )
    VALUES (
        s.AIRPORT_NAME, s.AIRPORT_COUNTRY_CODE,
        s.COUNTRY_NAME, s.AIRPORT_CONTINENT
    );

    -- DIM_PILOT
    MERGE INTO GOLD.DIM_PILOT t
    USING (
        SELECT 
            PILOT_NAME
        FROM GOLD.TMP_DATA
        WHERE PILOT_NAME IS NOT NULL
        QUALIFY ROW_NUMBER() OVER (
            PARTITION BY PILOT_NAME 
            ORDER BY DEPARTURE_DATE DESC
        ) = 1
    ) s
    ON t.PILOT_NAME = s.PILOT_NAME
    WHEN NOT MATCHED THEN INSERT (PILOT_NAME)
    VALUES (s.PILOT_NAME);

    -- DIM_DATE
    MERGE INTO GOLD.DIM_DATE t
    USING (
        SELECT 
            DEPARTURE_DATE AS FULL_DATE,
            YEAR(DEPARTURE_DATE) AS YEAR,
            MONTH(DEPARTURE_DATE) AS MONTH,
            DAY(DEPARTURE_DATE) AS DAY
        FROM GOLD.TMP_DATA
        WHERE DEPARTURE_DATE IS NOT NULL
        QUALIFY ROW_NUMBER() OVER (
            PARTITION BY DEPARTURE_DATE 
            ORDER BY DEPARTURE_DATE DESC
        ) = 1
    ) s
    ON t.FULL_DATE = s.FULL_DATE
    WHEN NOT MATCHED THEN INSERT (
        FULL_DATE, YEAR, MONTH, DAY
    )
    VALUES (
        s.FULL_DATE, s.YEAR, s.MONTH, s.DAY
    );

    -- FACT TABLE
    MERGE INTO GOLD.FACT_FLIGHTS t
    USING (
        SELECT
            dp.PASSENGER_KEY,
            d.DATE_KEY,
            a.AIRPORT_KEY,
            p.PILOT_KEY,
            s.TICKET_TYPE,
            s.FLIGHT_STATUS,
            s.PASSENGER_STATUS
        FROM GOLD.TMP_DATA s
        JOIN GOLD.DIM_PASSENGER dp 
            ON s.PASSENGER_ID = dp.PASSENGER_ID
        JOIN GOLD.DIM_DATE d 
            ON s.DEPARTURE_DATE = d.FULL_DATE
        JOIN GOLD.DIM_AIRPORT a 
            ON s.AIRPORT_NAME = a.AIRPORT_NAME
           AND s.AIRPORT_COUNTRY_CODE = a.AIRPORT_COUNTRY_CODE
        JOIN GOLD.DIM_PILOT p 
            ON s.PILOT_NAME = p.PILOT_NAME
        WHERE s.PASSENGER_ID IS NOT NULL
    ) s
    ON t.PASSENGER_KEY = s.PASSENGER_KEY 
       AND t.DATE_KEY = s.DATE_KEY
       AND t.AIRPORT_KEY = s.AIRPORT_KEY
       AND t.PILOT_KEY = s.PILOT_KEY

    WHEN NOT MATCHED THEN INSERT (
        PASSENGER_KEY, DATE_KEY, AIRPORT_KEY, PILOT_KEY,
        TICKET_TYPE, FLIGHT_STATUS, PASSENGER_STATUS
    )
    VALUES (
        s.PASSENGER_KEY, s.DATE_KEY, s.AIRPORT_KEY, s.PILOT_KEY,
        s.TICKET_TYPE, s.FLIGHT_STATUS, s.PASSENGER_STATUS
    );

    rows_affected := SQLROWCOUNT;

    -- Audit log
    INSERT INTO OPERATIONS.AUDIT_LOG 
    (SCHEMA_NAME, PIPELINE_STAGE, ROWS_AFFECTED, STATUS)
    VALUES ('GOLD', 'SILVER_TO_GOLD', :rows_affected, 'SUCCESS');

    COMMIT;

    RETURN 'Gold load complete';

EXCEPTION
    WHEN OTHER THEN
        ROLLBACK;
        
        INSERT INTO OPERATIONS.AUDIT_LOG 
        (SCHEMA_NAME, PIPELINE_STAGE, ROWS_AFFECTED, STATUS)
        VALUES ('GOLD', 'SILVER_TO_GOLD', 0, 'FAILED: ' || SQLERRM);
        
        RETURN 'Gold load failed: ' || SQLERRM;
END;
$$;






