USE DATABASE AIRLINE_EDW;
USE SCHEMA AIRLINE_EDW.GOLD;

CREATE OR REPLACE TABLE GOLD.DIM_PASSENGER (
    PASSENGER_KEY INT AUTOINCREMENT PRIMARY KEY,
    PASSENGER_ID VARCHAR,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    GENDER VARCHAR,
    AGE INT,
    NATIONALITY VARCHAR
);

CREATE OR REPLACE TABLE GOLD.DIM_AIRPORT (
    AIRPORT_KEY INT AUTOINCREMENT PRIMARY KEY,
    AIRPORT_NAME VARCHAR,
    AIRPORT_COUNTRY_CODE VARCHAR,
    COUNTRY_NAME VARCHAR,
    AIRPORT_CONTINENT VARCHAR
);

CREATE OR REPLACE TABLE GOLD.DIM_PILOT (
    PILOT_KEY INT AUTOINCREMENT PRIMARY KEY,
    PILOT_NAME VARCHAR
);

CREATE OR REPLACE TABLE GOLD.DIM_DATE (
    DATE_KEY INT AUTOINCREMENT PRIMARY KEY,
    FULL_DATE DATE,
    YEAR INT,
    MONTH INT,
    DAY INT
);

CREATE OR REPLACE TABLE GOLD.FACT_FLIGHTS (
    FACT_FLIGHT_KEY INT AUTOINCREMENT PRIMARY KEY,
    PASSENGER_KEY INT,
    DATE_KEY INT,
    AIRPORT_KEY INT,
    PILOT_KEY INT,
    TICKET_TYPE VARCHAR,
    FLIGHT_STATUS VARCHAR,
    PASSENGER_STATUS VARCHAR,

    FOREIGN KEY (PASSENGER_KEY) REFERENCES GOLD.DIM_PASSENGER(PASSENGER_KEY),
    FOREIGN KEY (DATE_KEY) REFERENCES GOLD.DIM_DATE(DATE_KEY),
    FOREIGN KEY (AIRPORT_KEY) REFERENCES GOLD.DIM_AIRPORT(AIRPORT_KEY),
    FOREIGN KEY (PILOT_KEY) REFERENCES GOLD.DIM_PILOT(PILOT_KEY)
);

