CREATE OR REPLACE SECURE VIEW GOLD.SECURE_FACT_FLIGHTS AS
SELECT 
    FACT_FLIGHT_KEY,
    PASSENGER_ID,
    DATE_KEY,
    AIRPORT_KEY,
    PILOT_KEY,
    TICKET_TYPE,
    FLIGHT_STATUS,
    PASSENGER_STATUS
FROM GOLD.FACT_FLIGHTS;

-- create new roles to test the policy
CREATE ROLE OPS_ANALYST;
CREATE ROLE GENERAL_ANALYST;

-- to change the policy, drop it first
ALTER VIEW GOLD.SECURE_FACT_FLIGHTS
DROP ROW ACCESS POLICY GOLD.STATUS_RLS_POLICY;

CREATE OR REPLACE ROW ACCESS POLICY GOLD.STATUS_RLS_POLICY
AS (status_val VARCHAR) RETURNS BOOLEAN ->
    CURRENT_ROLE() IN ('ACCOUNTADMIN', 'SYSADMIN')
    OR
    (CURRENT_ROLE() = 'OPS_ANALYST' AND status_val IN ('DELAYED', 'CANCELLED'))
    OR
    (CURRENT_ROLE() = 'GENERAL_ANALYST' AND status_val IN ('COMPLETED', 'ON TIME', 'SCHEDULED'));

ALTER VIEW GOLD.SECURE_FACT_FLIGHTS
ADD ROW ACCESS POLICY GOLD.STATUS_RLS_POLICY ON (FLIGHT_STATUS);

-- grant access to user shehabkh
GRANT ROLE OPS_ANALYST TO USER SHEHABK;
GRANT ROLE GENERAL_ANALYST TO USER SHEHABKH;
SELECT * FROM GOLD.SECURE_FACT_FLIGHTS