USE DATABASE AIRLINE_EDW;
USE SCHEMA AIRLINE_EDW.GOLD;

-- DML
-- 1
SELECT * FROM GOLD.FACT_FLIGHTS AT(OFFSET => -60*5); -- 5 mins ago

-- 2
-- delete from table
DELETE FROM GOLD.FACT_FLIGHTS
WHERE passenger_id = 'kPi6a7';

-- check table before delete statement
SELECT * FROM GOLD.FACT_FLIGHTS BEFORE (STATEMENT => '01c38274-0005-232d-0001-532600077ec2')

-- restore the record
INSERT INTO GOLD.FACT_FLIGHTS
SELECT * FROM GOLD.FACT_FLIGHTS BEFORE (STATEMENT => '01c38274-0005-232d-0001-532600077ec2')
WHERE passenger_id = 'kPi6a7';
 
-- DDL
-- 1
DROP TABLE GOLD.DIM_PILOT;
UNDROP TABLE GOLD.DIM_PILOT; 

-- 2
CREATE OR REPLACE TABLE GOLD.FACT_FLIGHTS_BACKUP 
CLONE GOLD.FACT_FLIGHTS AT(OFFSET => -60*60); -- one hour ago

