USE DATABASE AIRLINE_EDW;
USE SCHEMA AIRLINE_EDW.OPERATIONS;

CREATE OR REPLACE TABLE AUDIT_LOG (
    LOG_ID          INT AUTOINCREMENT PRIMARY KEY,
    SCHEMA_NAME     VARCHAR,
    PIPELINE_STAGE  VARCHAR,
    ROWS_AFFECTED   INT,
    STATUS          VARCHAR,
    EXECUTION_TIME  TIMESTAMP
);