USE DATABASE AIRLINE_EDW;
USE SCHEMA AIRLINE_EDW.BRONZE;


CREATE OR REPLACE PROCEDURE LOAD_RAW_DATA()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    rows_loaded INT;
BEGIN
    COPY INTO BRONZE.RAW
    FROM (
        -- Grabbing columns 2 through 18, ignoring the empty column 1
        SELECT 
            $2, $3, $4, $5, $6, $7, $8, $9, $10, 
            $11, $12, $13, $14, $15, $16, $17, $18
        FROM @BRONZE.INCOMING_STAGE
    )
    FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER = 1 ENCODING = 'UTF8');
    rows_loaded := SQLROWCOUNT;

    INSERT INTO OPERATIONS.AUDIT_LOG (SCHEMA_NAME, PIPELINE_STAGE, ROWS_AFFECTED, STATUS)
    VALUES ('BRONZE', 'STAGE_TO_BRONZE', :rows_loaded, 'SUCCESS');

    RETURN 'Bronze Load Complete. Rows loaded: ' || :rows_loaded;
END;
$$;

CREATE OR REPLACE PROCEDURE BRONZE.ARCHIVE_FILES()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
BEGIN
    COPY FILES INTO @BRONZE.ARCHIVE_STAGE 
    FROM @BRONZE.INCOMING_STAGE/;
    
    RETURN 'Success: Files copied to archive stage.';
END;
$$;

CREATE OR REPLACE PROCEDURE BRONZE.CLEANUP_INCOMING_STAGE()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
BEGIN
    REMOVE @BRONZE.INCOMING_STAGE PATTERN = '.*\.csv';
    RETURN 'Success: Incoming stage cleaned up.';
END;
$$;
